_unit = ODST_POD_CallerAI;
_AIpod = "TEI_HEV" createVehicle [0,0,10000];
_AIpod setPos [getmarkerPos "AIDrop" select 0, getmarkerPos "AIDrop" select 1, 500];
_AIpod setdir (random 360);
_AI = (group _unit) createUnit ["TEI_UNSC_ODST_Soldier", [0,0,10000], [], 20, "FORM"];
_AI moveindriver _AIpod;
[_AIPod, _AI] execVM "\tei_vehicles\hev\scripts\ODST_POD_LaunchAI.sqf";
waitUntil {vehicle _AI == _AI};
_unit addaction [("<t color=""#81BEF7"">" + ("Request ODST Support") +"</t>"),"\tei_vehicles\hev\scripts\ODST_POD_CallInAI.sqf", "", 7, true, true, "", "_this == _target"];
deletemarker "AIDrop";